### ISSUE TITLE
GeoWave Vagrant process fails due to incorrect directory paths

### ISSUE THREAD

**Issue by ScottEvil** [ngageoint/geowave-vagrant#1]
When I try to Vagrant up, it eventually fails with the message: cp: cannot stat `/home/vagrant/geowave/vagrant/geowave.sh': No such file or directory

I searched on the machine and the path where file resides is /home/vagrant/geowave/geowave.sh

Note also the failure on 'etc/init.d/geowave':

==> default: cp: cannot stat /home/vagrant/geowave/vagrant/geowave.sh': No such file or directory ==> default: chmod: cannot access/etc/init.d/geowave'
==> default: : No such file or directory
==> default: error reading information on service geowave: No such file or directory
==> default: geowave: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by chrisbennight** [comment]
Looks like you may have been the first victim of https://github.com/ngageoint/geowave/issues/320 - which was a non-trivial re-factor of the project.   

Fortunately looks like an easy fix, I'll run it down.

**Comment by ScottEvil** [comment]
That does look pretty substantial. Thanks for the quick response @chrisbennight

**Comment by chrisbennight** [comment]
#2 Should fix it (well, tested on my windows 8.1 box - that's the only one I have virtual box installed on)

**Comment by chrisbennight** [comment]
@ScottEvil when you get a chance, let me know if this works now - I'll leave the ticket open until then.

**Comment by rfecher** [comment]
I was trying to give this a shot on a fresh clone - vagrant up initially just takes a long time, but so far so good.

**Comment by ScottEvil** [comment]
"Vagrant up" works now! I was able to bring up the Accumulo page. I guess the next step is to build a geoserver with the jar so I have a data directory. Looks like this ticket can be closed.

**Comment by chrisbennight** [comment]
Thanks!
